#!/usr/bin/env bash

tmux new-session -d -s doral

tmux rename-window -t doral:1 'work'
tmux new-window -t doral:2 -n 'watch'

tmux send-keys -t doral:2 "gulp develop" C-m

tmux select-window -t doral:1
tmux attach-session -t doral
