#!/usr/bin/env bash

CD_PROJECT="cd ~/Projects/doralproperties/"

tmux new-session -d -s doral

tmux rename-window -t doral:1 'work'
tmux new-window -t doral:2 -n 'watch'

tmux send-keys -t doral:1 "$CD_PROJECT" C-m
tmux send-keys -t doral:2 "$CD_PROJECT" C-m 'compass watch' C-m

tmux select-window -t doral:1
tmux attach-session -t doral
