#!/usr/bin/env zsh

SESSION_NAME=doralproperties
PROJECT_DIR=$0:a:h

if tmux has-session -t $SESSION_NAME 2>/dev/null; then
  tmux attach -t $SESSION_NAME -d
  exit
fi

tmux new-session -d -s $SESSION_NAME -n work -c $PROJECT_DIR
tmux select-window -t $SESSION_NAME:1
tmux attach-session -t $SESSION_NAME
